/** @type {import('eslint-define-config').ESLintConfig} */
module.exports = {
  overrides: [
    {
      files: ['**/package.json'],
      parser: 'jsonc-eslint-parser',
      rules: {
        'jsonc/sort-keys': [
          'error',
          {
            pathPattern: '^$',
            order: [
              'name',
              'version',
              'private',
              'keywords',
              'categories',
              'description',
              'license',
              'author',
              'contributors',
              'funding',
              'homepage',
              'repository',
              'unpkg',
              'jsdelivr',
              'type',
              'main',
              'module',
              'types',
              'typesVersions',
              'exports',
              'bin',
              'icon',
              'files',
              'sideEffects',
              'packageManager',
              'scripts',
              'peerDependencies',
              'peerDependenciesMeta',
              'dependencies',
              'devDependencies',
              'bundleDependencies',
              'optionalDependencies',
              'engines',
              'pnpm',
              'overrides',
              'resolutions',
              'husky',
              'lint-staged',
              'simple-git-hooks',
              'prettier',
              'eslintConfig',
            ],
          },
          {
            pathPattern: '^(?:dev|peer|bundled|optional)?[Dd]ependencies$',
            order: { type: 'asc' },
          },
          {
            pathPattern: '^exports.*$',
            order: ['types', 'require', 'import'],
          },
        ],
      },
    },
  ],
}
